import { Hotel } from "@/types/hotel/hotel";

export const hotelData: Hotel[] = [
  {
    hotelId: 1,
    name: "Grand Hotel Amsterdam",
    location: "Amsterdam",
    description:
      "Ervaar luxe in het hart van Amsterdam bij Grand Hotel Amsterdam. Gelegen op loopafstand van de Grachten en het Rijksmuseum, biedt ons hotel prachtige uitzichten, wereldklasse dineren en onberispelijke service. Elke kamer is elegant ingericht met moderne voorzieningen en klassieke Amsterdamse charme.",
    rooms: [
      {
        id: 101,
        hotelId: 1,
        type: "Deluxe King Room",
        capacity: 2,
        pricePerNight: 250,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 102,
        hotelId: 1,
        type: "Executive Suite",
        capacity: 4,
        pricePerNight: 450,
        currency: "EUR",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
      {
        id: 103,
        hotelId: 1,
        type: "Standard Double Room",
        capacity: 2,
        pricePerNight: 180,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
    ],
    maxGuests: 4,
    pricePerNight: 250,
    amenities: [
      "Free WiFi",
      "Pool",
      "Spa",
      "Restaurant",
      "Bar",
      "Gym",
      "Room Service",
      "Concierge",
    ],
    starRating: 5,
    reviews: [
      { userId: 1, starRating: 5 },
      { userId: 2, starRating: 5 },
      { userId: 3, starRating: 4 },
      { userId: 4, starRating: 5 },
      { userId: 5, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 2,
    name: "Boutique Hotel De Grachten",
    location: "Amsterdam",
    description:
      "Ontdek de charme van Boutique Hotel De Grachten, gelegen aan de iconische Amsterdamse grachten. Geniet van unieke kamers met grachtenzicht, ontspan in onze lounge en proef de heerlijke lokale keuken. Perfect voor romantische uitjes en culturele verkenningen.",
    rooms: [
      {
        id: 201,
        hotelId: 2,
        type: "Grachten Suite",
        capacity: 3,
        pricePerNight: 195,
        currency: "EUR",
        maxGuests: 3,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 202,
        hotelId: 2,
        type: "Familie Kamer",
        capacity: 4,
        pricePerNight: 280,
        currency: "EUR",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.6,
      },
      {
        id: 203,
        hotelId: 2,
        type: "Standaard Kamer",
        capacity: 2,
        pricePerNight: 145,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
    ],
    maxGuests: 4,
    pricePerNight: 195,
    amenities: [
      "Gratis WiFi",
      "Grachtenzicht",
      "Restaurant",
      "Bar",
      "Fietsverhuur",
      "Parkeren",
    ],
    starRating: 4,
    reviews: [
      { userId: 6, starRating: 4 },
      { userId: 7, starRating: 5 },
      { userId: 8, starRating: 4 },
      { userId: 9, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 3,
    name: "Hotel New York Rotterdam",
    location: "Rotterdam",
    description:
      "Overnacht in het iconische Hotel New York aan de Maas, gehuisvest in het voormalige hoofdkantoor van de Holland Amerika Lijn. Geniet van de maritieme sfeer, het prachtige uitzicht over de rivier en moderne comfort. Perfect voor zakenreizigers en citytrippers.",
    rooms: [
      {
        id: 301,
        hotelId: 3,
        type: "Rivier Kamer",
        capacity: 2,
        pricePerNight: 165,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 302,
        hotelId: 3,
        type: "Familie Suite",
        capacity: 4,
        pricePerNight: 285,
        currency: "EUR",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 4,
    pricePerNight: 165,
    amenities: [
      "Gratis WiFi",
      "Restaurant",
      "Bar",
      "Terras",
      "Vergaderzalen",
      "Parkeren",
      "Uitzicht op Maas",
    ],
    starRating: 4,
    reviews: [
      { userId: 10, starRating: 4 },
      { userId: 11, starRating: 5 },
      { userId: 12, starRating: 4 },
      { userId: 13, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 4,
    name: "Boutique Hotel Den Haag",
    location: "Den Haag",
    description:
      "Ervaar hedendaagse elegantie in Boutique Hotel Den Haag, gelegen in het hart van de hofstad. Onze stijlvolle kamers combineren modern design met comfort, perfect voor zaken- en plezierreizigers. Op loopafstand van het Binnenhof, Madurodam en de beste restaurants van Den Haag.",
    rooms: [
      {
        id: 401,
        hotelId: 4,
        type: "Modern King Room",
        capacity: 2,
        pricePerNight: 210,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 402,
        hotelId: 4,
        type: "Business Suite",
        capacity: 2,
        pricePerNight: 320,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 403,
        hotelId: 4,
        type: "Twin Room",
        capacity: 2,
        pricePerNight: 180,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
    ],
    maxGuests: 2,
    pricePerNight: 210,
    amenities: [
      "Gratis WiFi",
      "Fitnessruimte",
      "Restaurant",
      "Bar",
      "24/7 Receptie",
      "Business Center",
      "Parkeren",
    ],
    starRating: 4,
    reviews: [
      { userId: 14, starRating: 4 },
      { userId: 15, starRating: 4 },
      { userId: 16, starRating: 5 },
      { userId: 17, starRating: 3 },
    ],
    images: [
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 5,
    name: "Strandhotel Scheveningen",
    location: "Scheveningen",
    description:
      "Ontspan bij Strandhotel Scheveningen, uw toegang tot de prachtige Nederlandse kust. Ons strandhotel biedt een schitterend uitzicht op de Noordzee, directe toegang tot het strand en een ontspannen sfeer. Geniet van verse vis en zeevruchten in ons restaurant met zeezicht.",
    rooms: [
      {
        id: 501,
        hotelId: 5,
        type: "Zeezicht Kamer",
        capacity: 2,
        pricePerNight: 175,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
      {
        id: 502,
        hotelId: 5,
        type: "Familie Zeezicht Suite",
        capacity: 4,
        pricePerNight: 295,
        currency: "EUR",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.6,
      },
    ],
    maxGuests: 4,
    pricePerNight: 175,
    amenities: [
      "Gratis WiFi",
      "Strand Toegang",
      "Restaurant",
      "Bar",
      "Terras",
      "Parkeren",
    ],
    starRating: 4,
    reviews: [
      { userId: 18, starRating: 4 },
      { userId: 19, starRating: 5 },
      { userId: 20, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 6,
    name: "Hotel Domstad Utrecht",
    location: "Utrecht",
    description:
      "Stap in de geschiedenis bij Hotel Domstad Utrecht, gelegen in het hart van de Domstad. Ons prachtig gerestaureerde pand combineert historische charme met modern comfort. Loop naar de Dom, de Oudegracht en geniet van heerlijke Nederlandse gerechten op ons dakterras.",
    rooms: [
      {
        id: 601,
        hotelId: 6,
        type: "Klassieke Tweepersoonskamer",
        capacity: 2,
        pricePerNight: 155,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 602,
        hotelId: 6,
        type: "Historische Suite",
        capacity: 3,
        pricePerNight: 265,
        currency: "EUR",
        maxGuests: 3,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 3,
    pricePerNight: 155,
    amenities: [
      "Gratis WiFi",
      "Dakterras",
      "Restaurant",
      "Bar",
      "Conciërge",
      "Fietsverhuur",
    ],
    starRating: 4,
    reviews: [
      { userId: 21, starRating: 5 },
      { userId: 22, starRating: 4 },
      { userId: 23, starRating: 4 },
      { userId: 24, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 7,
    name: "Business Hotel Haarlem",
    location: "Haarlem",
    description:
      "Business Hotel Haarlem is perfect voor moderne zakenreizigers die comfort en gemak zoeken in het centrum van Haarlem. Onze ruime suites beschikken over werkruimtes, keukens en snel internet. Ideaal voor langere verblijven met gemakkelijke toegang tot kantoren en het centrum.",
    rooms: [
      {
        id: 701,
        hotelId: 7,
        type: "Studio Suite",
        capacity: 2,
        pricePerNight: 135,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 702,
        hotelId: 7,
        type: "Eén Slaapkamer Suite",
        capacity: 3,
        pricePerNight: 185,
        currency: "EUR",
        maxGuests: 3,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 703,
        hotelId: 7,
        type: "Executive Twee Slaapkamers",
        capacity: 4,
        pricePerNight: 265,
        currency: "EUR",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.6,
      },
    ],
    maxGuests: 4,
    pricePerNight: 135,
    amenities: [
      "Gratis WiFi",
      "Fitnessruimte",
      "Business Center",
      "Vergaderzalen",
      "Wasservice",
      "Kitchenette",
      "Parkeren",
      "24/7 Receptie",
    ],
    starRating: 4,
    reviews: [
      { userId: 25, starRating: 4 },
      { userId: 26, starRating: 4 },
      { userId: 27, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
      "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 8,
    name: "Landgoed Hotel Den Bosch",
    location: "Den Bosch",
    description:
      "Ontsnap naar de serene schoonheid van Landgoed Hotel Den Bosch. Ons charmante landhuis is omgeven door groen en biedt een rustig toevluchtsoord. Geniet van wandelen door de Bossche bossen, proef de beroemde Bossche bollen en dineer met lokale seizoensproducten.",
    rooms: [
      {
        id: 801,
        hotelId: 8,
        type: "Tuin Kamer",
        capacity: 2,
        pricePerNight: 145,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 802,
        hotelId: 8,
        type: "Landgoed Suite",
        capacity: 2,
        pricePerNight: 195,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 803,
        hotelId: 8,
        type: "Familie Cottage",
        capacity: 5,
        pricePerNight: 325,
        currency: "EUR",
        maxGuests: 5,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 5,
    pricePerNight: 145,
    amenities: [
      "Gratis WiFi",
      "Restaurant",
      "Fietsverhuur",
      "Tuin",
      "Parkeren",
      "Huisdieren Toegestaan",
    ],
    starRating: 5,
    reviews: [
      { userId: 28, starRating: 5 },
      { userId: 29, starRating: 5 },
      { userId: 30, starRating: 5 },
      { userId: 31, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1549294413-26f195200c16?w=800",
      "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 9,
    name: "Hotel Giethoorn",
    location: "Giethoorn",
    description:
      "Ontdek de rust bij Hotel Giethoorn, gelegen in het Venetië van het Noorden. Ons boutique hotel biedt een prachtig uitzicht op de grachten, vaaractiviteiten en gezellige accommodaties. Perfect voor natuurliefhebbers en rust-zoekers.",
    rooms: [
      {
        id: 901,
        hotelId: 9,
        type: "Gracht Kamer",
        capacity: 2,
        pricePerNight: 165,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 902,
        hotelId: 9,
        type: "Luxe Suite",
        capacity: 4,
        pricePerNight: 285,
        currency: "EUR",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 4,
    pricePerNight: 165,
    amenities: [
      "Gratis WiFi",
      "Fluisterboten Verhuur",
      "Restaurant",
      "Bar",
      "Terras",
      "Parkeren",
    ],
    starRating: 4,
    reviews: [
      { userId: 32, starRating: 5 },
      { userId: 33, starRating: 4 },
      { userId: 34, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 10,
    name: "Budget Hotel Leiden",
    location: "Leiden",
    description:
      "Budget Hotel Leiden biedt uitstekende waarde in het hart van de historische stad Leiden. Schone, comfortabele kamers met essentiële voorzieningen maken het perfect voor budgetbewuste reizigers. Gelegen nabij het station voor gemakkelijke toegang tot de Hortus, musea en gezellige cafés.",
    rooms: [
      {
        id: 1001,
        hotelId: 10,
        type: "Standaard Kamer",
        capacity: 2,
        pricePerNight: 75,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
      {
        id: 1002,
        hotelId: 10,
        type: "Driepersoonskamer",
        capacity: 3,
        pricePerNight: 105,
        currency: "EUR",
        maxGuests: 3,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 1003,
        hotelId: 10,
        type: "Familie Kamer",
        capacity: 4,
        pricePerNight: 135,
        currency: "EUR",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
    ],
    maxGuests: 4,
    pricePerNight: 75,
    amenities: [
      "Gratis WiFi",
      "24/7 Receptie",
      "Bagage Opslag",
      "Informatiebalie",
      "Automaten",
    ],
    starRating: 3,
    reviews: [
      { userId: 35, starRating: 3 },
      { userId: 36, starRating: 4 },
      { userId: 37, starRating: 3 },
      { userId: 38, starRating: 3 },
    ],
    images: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
    ],
    currency: "EUR",
  },
  // Additional Amsterdam Hotels
  {
    hotelId: 11,
    name: "Budget Inn Amsterdam Centrum",
    location: "Amsterdam",
    description:
      "Budgetvriendelijk hotel in het centrum van Amsterdam. Schone, comfortabele kamers op loopafstand van het Centraal Station en de belangrijkste bezienswaardigheden.",
    rooms: [
      {
        id: 1101,
        hotelId: 11,
        type: "Standaard Kamer",
        capacity: 2,
        pricePerNight: 85,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
    ],
    maxGuests: 2,
    pricePerNight: 85,
    amenities: ["Gratis WiFi", "24/7 Receptie", "Bagage Opslag"],
    starRating: 3,
    reviews: [
      { userId: 100, starRating: 3 },
      { userId: 101, starRating: 4 },
    ],
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"],
    currency: "EUR",
  },
  {
    hotelId: 12,
    name: "Hotel De Jordaan",
    location: "Amsterdam",
    description:
      "Gezellig hotel in de trendy Jordaan wijk. Omringd door leuke cafés, winkels en kunstgaleries.",
    rooms: [
      {
        id: 1201,
        hotelId: 12,
        type: "Comfort Tweepersoonskamer",
        capacity: 2,
        pricePerNight: 145,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
    ],
    maxGuests: 2,
    pricePerNight: 145,
    amenities: ["Gratis WiFi", "Fietsverhuur", "Bar", "Ontbijt"],
    starRating: 4,
    reviews: [
      { userId: 102, starRating: 4 },
      { userId: 103, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 13,
    name: "Amsterdam Business Suites",
    location: "Amsterdam",
    description:
      "Moderne zakelijke accommodatie met volledig uitgeruste suites. Ideaal voor langere verblijven en zakenreizigers.",
    rooms: [
      {
        id: 1301,
        hotelId: 13,
        type: "Studio Suite",
        capacity: 2,
        pricePerNight: 165,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
    ],
    maxGuests: 2,
    pricePerNight: 165,
    amenities: [
      "Gratis WiFi",
      "Fitnessruimte",
      "Business Center",
      "Kitchenette",
    ],
    starRating: 4,
    reviews: [{ userId: 104, starRating: 4 }],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 14,
    name: "Hotel Museumplein",
    location: "Amsterdam",
    description:
      "Elegant hotel nabij het Museumplein en Van Gogh Museum. Perfect voor cultuurliefhebbers.",
    rooms: [
      {
        id: 1401,
        hotelId: 14,
        type: "Superior Kamer",
        capacity: 2,
        pricePerNight: 220,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
    ],
    maxGuests: 2,
    pricePerNight: 220,
    amenities: ["Gratis WiFi", "Restaurant", "Bar", "Conciërge"],
    starRating: 4,
    reviews: [
      { userId: 105, starRating: 5 },
      { userId: 106, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 15,
    name: "Amsterdam Oost Urban Hotel",
    location: "Amsterdam",
    description:
      "Hip en modern hotel in Amsterdam Oost, de opkomende creatieve wijk van de stad.",
    rooms: [
      {
        id: 1501,
        hotelId: 15,
        type: "Urban Kamer",
        capacity: 2,
        pricePerNight: 125,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
    ],
    maxGuests: 2,
    pricePerNight: 125,
    amenities: ["Gratis WiFi", "Bar", "Fietsverhuur", "Terras"],
    starRating: 3,
    reviews: [{ userId: 107, starRating: 4 }],
    images: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 16,
    name: "The Amsterdam Canal House",
    location: "Amsterdam",
    description:
      "Luxe boetiekhotel in een 17e-eeuws grachtenpand. Authentieke Amsterdamse charme met moderne luxe.",
    rooms: [
      {
        id: 1601,
        hotelId: 16,
        type: "Canal View Room",
        capacity: 2,
        pricePerNight: 295,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 2,
    pricePerNight: 295,
    amenities: ["Gratis WiFi", "Grachtenzicht", "Conciërge", "Roomservice"],
    starRating: 5,
    reviews: [
      { userId: 108, starRating: 5 },
      { userId: 109, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    ],
    currency: "EUR",
  },
  // Additional Rotterdam Hotels
  {
    hotelId: 17,
    name: "Rotterdam Skyline Hotel",
    location: "Rotterdam",
    description:
      "Modern hoogbouw hotel met spectaculair uitzicht over de Rotterdamse skyline.",
    rooms: [
      {
        id: 1701,
        hotelId: 17,
        type: "Skyline Kamer",
        capacity: 2,
        pricePerNight: 135,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
    ],
    maxGuests: 2,
    pricePerNight: 135,
    amenities: ["Gratis WiFi", "Fitnessruimte", "Bar", "24/7 Receptie"],
    starRating: 4,
    reviews: [{ userId: 110, starRating: 4 }],
    images: [
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 18,
    name: "Budget Hotel Rotterdam Zuid",
    location: "Rotterdam",
    description:
      "Budgetvriendelijk hotel met goede verbindingen naar het centrum en Ahoy.",
    rooms: [
      {
        id: 1801,
        hotelId: 18,
        type: "Basis Kamer",
        capacity: 2,
        pricePerNight: 70,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
    ],
    maxGuests: 2,
    pricePerNight: 70,
    amenities: ["Gratis WiFi", "Parkeren", "24/7 Receptie"],
    starRating: 2,
    reviews: [{ userId: 111, starRating: 3 }],
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"],
    currency: "EUR",
  },
  {
    hotelId: 19,
    name: "Boutique Hotel Witte de With",
    location: "Rotterdam",
    description:
      "Trendy boetiekhotel in het kunstenaarsdistrict. Perfect voor culturele exploratie.",
    rooms: [
      {
        id: 1901,
        hotelId: 19,
        type: "Design Kamer",
        capacity: 2,
        pricePerNight: 155,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
    ],
    maxGuests: 2,
    pricePerNight: 155,
    amenities: ["Gratis WiFi", "Bar", "Kunstgalerie", "Ontbijt"],
    starRating: 4,
    reviews: [{ userId: 112, starRating: 5 }],
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 20,
    name: "The Rotterdam Luxury",
    location: "Rotterdam",
    description:
      "Vijfsterren luxe hotel met panoramisch uitzicht op de Erasmusbrug. Top service en spa faciliteiten.",
    rooms: [
      {
        id: 2001,
        hotelId: 20,
        type: "Deluxe Kamer",
        capacity: 2,
        pricePerNight: 275,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 2,
    pricePerNight: 275,
    amenities: ["Gratis WiFi", "Spa", "Zwembad", "Restaurant", "Roomservice"],
    starRating: 5,
    reviews: [
      { userId: 113, starRating: 5 },
      { userId: 114, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
    ],
    currency: "EUR",
  },
  // Additional Den Haag Hotels
  {
    hotelId: 21,
    name: "Den Haag Budget Inn",
    location: "Den Haag",
    description: "Betaalbaar hotel nabij Den Haag Centraal Station.",
    rooms: [
      {
        id: 2101,
        hotelId: 21,
        type: "Standaard Tweepersoonskamer",
        capacity: 2,
        pricePerNight: 80,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
    ],
    maxGuests: 2,
    pricePerNight: 80,
    amenities: ["Gratis WiFi", "24/7 Receptie"],
    starRating: 2,
    reviews: [{ userId: 115, starRating: 3 }],
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"],
    currency: "EUR",
  },
  {
    hotelId: 22,
    name: "Hotel des Indes Den Haag",
    location: "Den Haag",
    description:
      "Historisch luxe hotel met koninklijke allure. Ongeëvenaarde elegantie en service.",
    rooms: [
      {
        id: 2201,
        hotelId: 22,
        type: "Superior Kamer",
        capacity: 2,
        pricePerNight: 325,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 2,
    pricePerNight: 325,
    amenities: ["Gratis WiFi", "Restaurant", "Bar", "Spa", "Roomservice"],
    starRating: 5,
    reviews: [
      { userId: 116, starRating: 5 },
      { userId: 117, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 23,
    name: "Den Haag Business Hotel",
    location: "Den Haag",
    description:
      "Functioneel zakenhotel nabij overheidsgebouwen. Perfect voor zakelijke gasten.",
    rooms: [
      {
        id: 2301,
        hotelId: 23,
        type: "Business Kamer",
        capacity: 2,
        pricePerNight: 145,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
    ],
    maxGuests: 2,
    pricePerNight: 145,
    amenities: ["Gratis WiFi", "Business Center", "Vergaderzalen", "Parkeren"],
    starRating: 3,
    reviews: [{ userId: 118, starRating: 4 }],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
    ],
    currency: "EUR",
  },
  // Additional Utrecht Hotels
  {
    hotelId: 24,
    name: "Utrecht Budget Lodge",
    location: "Utrecht",
    description: "Budgetvriendelijke accommodatie nabij Utrecht Centraal.",
    rooms: [
      {
        id: 2401,
        hotelId: 24,
        type: "Basis Kamer",
        capacity: 2,
        pricePerNight: 75,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
    ],
    maxGuests: 2,
    pricePerNight: 75,
    amenities: ["Gratis WiFi", "24/7 Receptie"],
    starRating: 2,
    reviews: [{ userId: 119, starRating: 3 }],
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"],
    currency: "EUR",
  },
  {
    hotelId: 25,
    name: "Grand Hotel Karel V",
    location: "Utrecht",
    description:
      "Luxueus vijfsterren hotel in een voormalig klooster uit de 14e eeuw.",
    rooms: [
      {
        id: 2501,
        hotelId: 25,
        type: "Deluxe Kamer",
        capacity: 2,
        pricePerNight: 295,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 2,
    pricePerNight: 295,
    amenities: ["Gratis WiFi", "Spa", "Restaurant", "Bar", "Tuin"],
    starRating: 5,
    reviews: [
      { userId: 120, starRating: 5 },
      { userId: 121, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 26,
    name: "Boutique Hotel Oudegracht",
    location: "Utrecht",
    description: "Charmant boetiekhotel direct aan de beroemde Oudegracht.",
    rooms: [
      {
        id: 2601,
        hotelId: 26,
        type: "Canal View Room",
        capacity: 2,
        pricePerNight: 185,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
    ],
    maxGuests: 2,
    pricePerNight: 185,
    amenities: ["Gratis WiFi", "Grachtenzicht", "Bar", "Fietsverhuur"],
    starRating: 4,
    reviews: [{ userId: 122, starRating: 5 }],
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
    ],
    currency: "EUR",
  },
  // Additional Haarlem Hotels
  {
    hotelId: 27,
    name: "Carlton Square Hotel Haarlem",
    location: "Haarlem",
    description:
      "Elegant hotel aan de Grote Markt met uitzicht op de St. Bavo kerk.",
    rooms: [
      {
        id: 2701,
        hotelId: 27,
        type: "Comfort Kamer",
        capacity: 2,
        pricePerNight: 145,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
    ],
    maxGuests: 2,
    pricePerNight: 145,
    amenities: ["Gratis WiFi", "Restaurant", "Bar", "Terras"],
    starRating: 4,
    reviews: [
      { userId: 123, starRating: 4 },
      { userId: 124, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 28,
    name: "Haarlem Budget Inn",
    location: "Haarlem",
    description: "Betaalbaar hotel nabij Haarlem Station.",
    rooms: [
      {
        id: 2801,
        hotelId: 28,
        type: "Standaard Kamer",
        capacity: 2,
        pricePerNight: 70,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
    ],
    maxGuests: 2,
    pricePerNight: 70,
    amenities: ["Gratis WiFi", "24/7 Receptie", "Parkeren"],
    starRating: 2,
    reviews: [{ userId: 125, starRating: 3 }],
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"],
    currency: "EUR",
  },
  {
    hotelId: 29,
    name: "Boutique Hotel Staats Haarlem",
    location: "Haarlem",
    description: "Karaktervol boetiekhotel in een monumentaal pand.",
    rooms: [
      {
        id: 2901,
        hotelId: 29,
        type: "Superior Kamer",
        capacity: 2,
        pricePerNight: 175,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
    ],
    maxGuests: 2,
    pricePerNight: 175,
    amenities: ["Gratis WiFi", "Bar", "Ontbijt", "Conciërge"],
    starRating: 4,
    reviews: [{ userId: 126, starRating: 5 }],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 30,
    name: "Hotel de Filosoof Haarlem",
    location: "Haarlem",
    description: "Uniek themahotel waar elke kamer gewijd is aan een filosoof.",
    rooms: [
      {
        id: 3001,
        hotelId: 30,
        type: "Thema Kamer",
        capacity: 2,
        pricePerNight: 115,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
    ],
    maxGuests: 2,
    pricePerNight: 115,
    amenities: ["Gratis WiFi", "Tuin", "Ontbijt", "Bibliotheek"],
    starRating: 3,
    reviews: [{ userId: 127, starRating: 4 }],
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
    ],
    currency: "EUR",
  },
  // Additional Leiden Hotels
  {
    hotelId: 31,
    name: "Hotel Leiden Centre",
    location: "Leiden",
    description: "Modern hotel in het historische centrum van Leiden.",
    rooms: [
      {
        id: 3101,
        hotelId: 31,
        type: "Standaard Kamer",
        capacity: 2,
        pricePerNight: 95,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
    ],
    maxGuests: 2,
    pricePerNight: 95,
    amenities: ["Gratis WiFi", "Restaurant", "Bar", "Fietsverhuur"],
    starRating: 3,
    reviews: [{ userId: 128, starRating: 4 }],
    images: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 32,
    name: "Boutique Hotel d'Oude Morsch",
    location: "Leiden",
    description: "Charmant boetiekhotel aan de Rapenburg gracht.",
    rooms: [
      {
        id: 3201,
        hotelId: 32,
        type: "Deluxe Kamer",
        capacity: 2,
        pricePerNight: 155,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
    ],
    maxGuests: 2,
    pricePerNight: 155,
    amenities: ["Gratis WiFi", "Grachtenzicht", "Bar", "Fietsverhuur"],
    starRating: 4,
    reviews: [{ userId: 129, starRating: 5 }],
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
    ],
    currency: "EUR",
  },
];
