import { Hotel } from "@/types/hotel/hotel";

export const hotelData: Hotel[] = [
  {
    hotelId: 1,
    name: "The Grand Plaza Hotel",
    location: "Paris, France",
    description:
      "Experience luxury in the heart of Paris at The Grand Plaza Hotel. Located steps away from the Eiffel Tower, our hotel offers stunning views, world-class dining, and impeccable service. Each room is elegantly appointed with modern amenities and classic Parisian charm.",
    rooms: [
      {
        id: 101,
        hotelId: 1,
        type: "Deluxe King Room",
        capacity: 2,
        pricePerNight: 250,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 102,
        hotelId: 1,
        type: "Executive Suite",
        capacity: 4,
        pricePerNight: 450,
        currency: "EUR",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
      {
        id: 103,
        hotelId: 1,
        type: "Standard Double Room",
        capacity: 2,
        pricePerNight: 180,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
    ],
    maxGuests: 4,
    pricePerNight: 250,
    amenities: [
      "Free WiFi",
      "Pool",
      "Spa",
      "Restaurant",
      "Bar",
      "Gym",
      "Room Service",
      "Concierge",
    ],
    starRating: 5,
    reviews: [
      { userId: 1, starRating: 5 },
      { userId: 2, starRating: 5 },
      { userId: 3, starRating: 4 },
      { userId: 4, starRating: 5 },
      { userId: 5, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 2,
    name: "Seaside Resort & Spa",
    location: "Sydney, Australia",
    description:
      "Discover paradise at Seaside Resort & Spa, where golden beaches meet luxury accommodation. Wake up to breathtaking ocean views, enjoy our infinity pool, and indulge in authentic Australian cuisine. Perfect for both romantic getaways and family vacations.",
    rooms: [
      {
        id: 201,
        hotelId: 2,
        type: "Ocean View Suite",
        capacity: 3,
        pricePerNight: 320,
        currency: "AUD",
        maxGuests: 3,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 202,
        hotelId: 2,
        type: "Family Beachfront Villa",
        capacity: 6,
        pricePerNight: 580,
        currency: "AUD",
        maxGuests: 6,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.6,
      },
      {
        id: 203,
        hotelId: 2,
        type: "Garden View Room",
        capacity: 2,
        pricePerNight: 220,
        currency: "AUD",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
    ],
    maxGuests: 6,
    pricePerNight: 320,
    amenities: [
      "Free WiFi",
      "Beach Access",
      "Pool",
      "Spa",
      "Restaurant",
      "Water Sports",
      "Kids Club",
      "Parking",
    ],
    starRating: 5,
    reviews: [
      { userId: 6, starRating: 5 },
      { userId: 7, starRating: 5 },
      { userId: 8, starRating: 5 },
      { userId: 9, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800",
    ],
    currency: "AUD",
  },
  {
    hotelId: 3,
    name: "Mountain View Lodge",
    location: "Chamonix, France",
    description:
      "Nestled in the French Alps, Mountain View Lodge offers cozy comfort with spectacular mountain vistas. Ideal for ski enthusiasts and nature lovers, our lodge features rustic charm combined with modern amenities. Enjoy traditional Alpine cuisine in our mountain-view restaurant.",
    rooms: [
      {
        id: 301,
        hotelId: 3,
        type: "Alpine Chalet Room",
        capacity: 2,
        pricePerNight: 190,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 302,
        hotelId: 3,
        type: "Family Mountain Suite",
        capacity: 5,
        pricePerNight: 380,
        currency: "EUR",
        maxGuests: 5,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 5,
    pricePerNight: 190,
    amenities: [
      "Free WiFi",
      "Ski Storage",
      "Restaurant",
      "Bar",
      "Sauna",
      "Fireplace",
      "Parking",
      "Shuttle Service",
    ],
    starRating: 4,
    reviews: [
      { userId: 10, starRating: 4 },
      { userId: 11, starRating: 5 },
      { userId: 12, starRating: 4 },
      { userId: 13, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 4,
    name: "Urban Boutique Hotel",
    location: "London, United Kingdom",
    description:
      "Experience contemporary elegance at Urban Boutique Hotel in the heart of London. Our stylish rooms blend modern design with comfort, perfect for business and leisure travelers. Walking distance to major attractions, shopping, and the best of London's dining scene.",
    rooms: [
      {
        id: 401,
        hotelId: 4,
        type: "Modern King Room",
        capacity: 2,
        pricePerNight: 210,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 402,
        hotelId: 4,
        type: "Business Suite",
        capacity: 2,
        pricePerNight: 320,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 403,
        hotelId: 4,
        type: "Twin Room",
        capacity: 2,
        pricePerNight: 180,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
    ],
    maxGuests: 2,
    pricePerNight: 210,
    amenities: [
      "Free WiFi",
      "Gym",
      "Restaurant",
      "Bar",
      "24/7 Reception",
      "Business Center",
      "Airport Shuttle",
    ],
    starRating: 4,
    reviews: [
      { userId: 14, starRating: 4 },
      { userId: 15, starRating: 4 },
      { userId: 16, starRating: 5 },
      { userId: 17, starRating: 3 },
    ],
    images: [
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 5,
    name: "Coastal Paradise Inn",
    location: "Gold Coast, Australia",
    description:
      "Relax at Coastal Paradise Inn, your gateway to Australia's famous Gold Coast beaches. Our beachfront property offers stunning ocean views, easy beach access, and a laid-back atmosphere perfect for unwinding. Enjoy fresh seafood at our oceanfront restaurant.",
    rooms: [
      {
        id: 501,
        hotelId: 5,
        type: "Beachfront Room",
        capacity: 2,
        pricePerNight: 280,
        currency: "AUD",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
      {
        id: 502,
        hotelId: 5,
        type: "Ocean View Suite",
        capacity: 4,
        pricePerNight: 420,
        currency: "AUD",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.6,
      },
    ],
    maxGuests: 4,
    pricePerNight: 280,
    amenities: [
      "Free WiFi",
      "Beach Access",
      "Pool",
      "Restaurant",
      "Surfboard Rental",
      "BBQ Area",
      "Parking",
    ],
    starRating: 4,
    reviews: [
      { userId: 18, starRating: 4 },
      { userId: 19, starRating: 5 },
      { userId: 20, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1559508551-44bff1de756b?w=800",
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    ],
    currency: "AUD",
  },
  {
    hotelId: 6,
    name: "Historic City Center Hotel",
    location: "Rome, Italy",
    description:
      "Step into history at Historic City Center Hotel, located in the heart of ancient Rome. Our beautifully restored 18th-century building combines historical charm with modern comfort. Walk to the Colosseum, Trevi Fountain, and enjoy authentic Italian cuisine at our rooftop terrace.",
    rooms: [
      {
        id: 601,
        hotelId: 6,
        type: "Classic Double Room",
        capacity: 2,
        pricePerNight: 195,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 602,
        hotelId: 6,
        type: "Historic Suite",
        capacity: 3,
        pricePerNight: 350,
        currency: "EUR",
        maxGuests: 3,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 3,
    pricePerNight: 195,
    amenities: [
      "Free WiFi",
      "Rooftop Terrace",
      "Restaurant",
      "Bar",
      "Concierge",
      "Tour Desk",
      "Bike Rental",
    ],
    starRating: 4,
    reviews: [
      { userId: 21, starRating: 5 },
      { userId: 22, starRating: 4 },
      { userId: 23, starRating: 4 },
      { userId: 24, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 7,
    name: "Downtown Business Suites",
    location: "Melbourne, Australia",
    description:
      "Downtown Business Suites caters to modern business travelers seeking comfort and convenience in Melbourne's CBD. Our spacious suites feature full kitchens, work areas, and high-speed internet. Perfect for extended stays with easy access to corporate offices and entertainment.",
    rooms: [
      {
        id: 701,
        hotelId: 7,
        type: "Studio Suite",
        capacity: 2,
        pricePerNight: 240,
        currency: "AUD",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 702,
        hotelId: 7,
        type: "One Bedroom Suite",
        capacity: 3,
        pricePerNight: 340,
        currency: "AUD",
        maxGuests: 3,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 703,
        hotelId: 7,
        type: "Executive Two Bedroom",
        capacity: 4,
        pricePerNight: 480,
        currency: "AUD",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.6,
      },
    ],
    maxGuests: 4,
    pricePerNight: 240,
    amenities: [
      "Free WiFi",
      "Gym",
      "Business Center",
      "Meeting Rooms",
      "Laundry",
      "Kitchenette",
      "Parking",
      "24/7 Reception",
    ],
    starRating: 4,
    reviews: [
      { userId: 25, starRating: 4 },
      { userId: 26, starRating: 4 },
      { userId: 27, starRating: 5 },
    ],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
      "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800",
    ],
    currency: "AUD",
  },
  {
    hotelId: 8,
    name: "Countryside Manor",
    location: "Provence, France",
    description:
      "Escape to the serene beauty of Countryside Manor in the heart of Provence. Our charming manor house is surrounded by lavender fields and vineyards, offering a peaceful retreat. Enjoy wine tasting, cycling through picturesque villages, and farm-to-table dining.",
    rooms: [
      {
        id: 801,
        hotelId: 8,
        type: "Garden View Room",
        capacity: 2,
        pricePerNight: 165,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 802,
        hotelId: 8,
        type: "Vineyard Suite",
        capacity: 2,
        pricePerNight: 245,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 803,
        hotelId: 8,
        type: "Family Cottage",
        capacity: 5,
        pricePerNight: 395,
        currency: "EUR",
        maxGuests: 5,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 5,
    pricePerNight: 165,
    amenities: [
      "Free WiFi",
      "Pool",
      "Restaurant",
      "Wine Tasting",
      "Bike Rental",
      "Garden",
      "Parking",
      "Pet Friendly",
    ],
    starRating: 5,
    reviews: [
      { userId: 28, starRating: 5 },
      { userId: 29, starRating: 5 },
      { userId: 30, starRating: 5 },
      { userId: 31, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1549294413-26f195200c16?w=800",
      "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    ],
    currency: "EUR",
  },
  {
    hotelId: 9,
    name: "Lakeside Retreat",
    location: "Queenstown, New Zealand",
    description:
      "Discover tranquility at Lakeside Retreat on the shores of Lake Wakatipu. Our boutique hotel offers breathtaking lake and mountain views, adventure activities, and cozy accommodations. Perfect for both thrill-seekers and those seeking peaceful relaxation in nature.",
    rooms: [
      {
        id: 901,
        hotelId: 9,
        type: "Lake View Room",
        capacity: 2,
        pricePerNight: 290,
        currency: "AUD",
        maxGuests: 2,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
      {
        id: 902,
        hotelId: 9,
        type: "Mountain Suite",
        capacity: 4,
        pricePerNight: 450,
        currency: "AUD",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.5,
      },
    ],
    maxGuests: 4,
    pricePerNight: 290,
    amenities: [
      "Free WiFi",
      "Lake Access",
      "Restaurant",
      "Bar",
      "Spa",
      "Adventure Tours",
      "Kayak Rental",
      "Parking",
    ],
    starRating: 5,
    reviews: [
      { userId: 32, starRating: 5 },
      { userId: 33, starRating: 5 },
      { userId: 34, starRating: 4 },
    ],
    images: [
      "https://images.unsplash.com/photo-1587009825628-47acd1b6e980?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
      "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800",
    ],
    currency: "AUD",
  },
  {
    hotelId: 10,
    name: "Budget Comfort Inn",
    location: "Barcelona, Spain",
    description:
      "Budget Comfort Inn offers excellent value in the heart of Barcelona. Clean, comfortable rooms with essential amenities make it perfect for budget-conscious travelers. Located near metro stations for easy access to La Sagrada Familia, Gothic Quarter, and beautiful beaches.",
    rooms: [
      {
        id: 1001,
        hotelId: 10,
        type: "Standard Room",
        capacity: 2,
        pricePerNight: 95,
        currency: "EUR",
        maxGuests: 2,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.2,
      },
      {
        id: 1002,
        hotelId: 10,
        type: "Triple Room",
        capacity: 3,
        pricePerNight: 130,
        currency: "EUR",
        maxGuests: 3,
        hasBreakfast: false,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.3,
      },
      {
        id: 1003,
        hotelId: 10,
        type: "Family Room",
        capacity: 4,
        pricePerNight: 165,
        currency: "EUR",
        maxGuests: 4,
        hasBreakfast: true,
        isAvailable: (checkIn: Date, checkOut: Date) => Math.random() > 0.4,
      },
    ],
    maxGuests: 4,
    pricePerNight: 95,
    amenities: [
      "Free WiFi",
      "24/7 Reception",
      "Luggage Storage",
      "Tour Desk",
      "Vending Machines",
      "Air Conditioning",
    ],
    starRating: 3,
    reviews: [
      { userId: 35, starRating: 3 },
      { userId: 36, starRating: 4 },
      { userId: 37, starRating: 3 },
      { userId: 38, starRating: 3 },
    ],
    images: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
    ],
    currency: "EUR",
  },
];
